### ISSUE TITLE
Can't export VF with UnnestComponents ticked ("not compatible")

### ISSUE THREAD

**Issue by cdeliason** [mekkablue/UnnestComponents#2]
UnnestComponents when checked is not allowing me to successfully export a variable font. 

The error message I get when trying to export: “These glyphs are not compatible…”
They look fine to me with Show Master Compatibility and Show Variable Font Preview 3, and don’t have the red bar above.
Error disappears if I uncheck “UnnestComponents” in the VF custom parameters.

Issue first flagged at https://forum.glyphsapp.com/t/unnestcomponents-in-vf/28725/10

In an email Georg  noted "It seems that the filter is only decomposing the default layer" (and asked me to create this issue).

**Comment by eweracs** [comment]
Is this still the case? The updated logic from Feb 29 last year should fix this.

**Comment by cdeliason** [comment]
Since I posted this I converted the project to non-variable so I can't easily test whether the error persists.

**Comment by eweracs** [comment]
I think you can safely close this issue, the improved logic takes care of nested components in all masters.
